openapi: 3.0.3
info:
  title: OpenAPI schema for template.
components:
  schemas:
    variables:
      required:
      - namespace
      type: object
      properties:
        namespace:
          title: Namespace
          type: string
          description: Name of the namespace resource.
          x-walrus-ui:
            group: Basic
            order: 1
        quota_limits_cpu:
          title: Quota Limits CPU
          type: string
          description: CPU limits quota of the namespace. e.g. 0.5, 1, 2, 4
          default: 4
          enum:
            - 0.5
            - 1
            - 2
            - 4
          x-walrus-ui:
            group: Quota
            order: 2
        quota_limits_memory:
          title: Quota Limits Memory
          type: string
          description: Memory limits quota of the namespace. e.g. 512, 2048, 4096, 8192
          default: 4096
          enum:
            - 2048
            - 4096
            - 8192
          x-walrus-ui:
            group: Quota
            order: 3
            widget: Memory
        quota_requests_cpu:
          title: Quota Requests CPU
          type: string
          description: CPU requests quota of the namespace. e.g. 0.5, 1, 2, 4
          default: 2
          enum:
            - 0.5
            - 1
            - 2
            - 4
          x-walrus-ui:
            group: Quota
            order: 4
        quota_requests_memory:
          title: Quota Requests Memory
          type: string
          description: Memory requests quota of the namespace. e.g. 512, 2048, 4096, 8192
          default: 2048
          enum:
            - 2048
            - 4096
            - 8192
          x-walrus-ui:
            group: Quota
            order: 5
            widget: Memory
        default_limits_cpu:
          title: Default Limits CPU
          type: string
          description: Default CPU limits of containers in the namespace. e.g. 0.1, 0.5, 1, 2
          default: 0.1
          enum:
            - 0.1
            - 0.2
            - 0.5
          x-walrus-ui:
            group: Limits
            order: 6
            immutable: true
        default_limits_memory:
          title: Default Limits Memory
          type: string
          description: Default memory limits of containers in the namespace. e.g. 128, 256, 512, 1024
          default: 128
          enum:
            - 128
            - 256
            - 512
            - 1024
          x-walrus-ui:
            group: Limits
            order: 7
            widget: Memory
            immutable: true
        default_requests_cpu:
          title: Default Requests CPU
          type: string
          description: Default CPU requests of containers in the namespace. e.g. 0.1, 0.5, 1, 2
          default: 0.1
          enum:
            - 0.1
            - 0.2
            - 0.5
          x-walrus-ui:
            group: Limits
            order: 8
            immutable: true
        default_requests_memory:
          title: Default Requests Memory
          type: string
          description: Default memory requests of containers in the namespace. e.g. 128, 256, 512, 1024
          default: 128
          enum:
            - 128
            - 256
            - 512
            - 1024
          x-walrus-ui:
            group: Limits
            order: 9
            widget: Memory
            immutable: true
        walrus_metadata_service_name:
          title: Walrus Metadata Service Name
          type: string
          description: Walrus metadata service name.
          default: ""
          x-walrus-ui:
            group: Basic
            order: 10
            hidden: true
        walrus_metadata_namespace_name:
          title: Walrus Metadata Namespace Name
          type: string
          description: Walrus metadata namespace name.
          default: ""
          x-walrus-ui:
            group: Basic
            order: 11
            hidden: true
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 12
