openapi: 3.0.3
info:
  title: OpenAPI schema for template kubernetes-namespace
components:
  schemas:
    variables:
      type: object
      required:
      - namespace
      properties:
        namespace:
          title: Namespace
          type: string
          description: Name of the namespace resource.
          x-walrus-ui:
            order: 1
        quota_limits_cpu:
          title: Quota Limits Cpu
          type: string
          description: CPU limits quota of the namespace. e.g. 0.5, 1, 2, 4
          default: ""
          nullable: true
          x-walrus-ui:
            order: 2
        quota_limits_memory:
          title: Quota Limits Memory
          type: string
          description: Memory limits quota of the namespace. e.g. 512Mi, 2Gi, 4Gi,
            8Gi
          default: ""
          nullable: true
          x-walrus-ui:
            order: 3
        quota_requests_cpu:
          title: Quota Requests Cpu
          type: string
          description: CPU requests quota of the namespace. e.g. 0.5, 1, 2, 4
          default: ""
          nullable: true
          x-walrus-ui:
            order: 4
        quota_requests_memory:
          title: Quota Requests Memory
          type: string
          description: Memory requests quota of the namespace. e.g. 512Mi, 2Gi, 4Gi,
            8Gi
          default: ""
          nullable: true
          x-walrus-ui:
            order: 5
        default_limits_cpu:
          title: Default Limits Cpu
          type: string
          description: Default CPU limits of containers in the namespace. e.g. 0.05,
            0.1, 0.5, 1, 2
          default: ""
          nullable: true
          x-walrus-ui:
            order: 6
        default_limits_memory:
          title: Default Limits Memory
          type: string
          description: Default memory limits of containers in the namespace. e.g.
            128Mi, 256Mi, 512Mi, 1Gi
          default: ""
          nullable: true
          x-walrus-ui:
            order: 7
        default_requests_cpu:
          title: Default Requests Cpu
          type: string
          description: Default CPU requests of containers in the namespace. e.g. 0.05,
            0.1, 0.5, 1, 2
          default: ""
          nullable: true
          x-walrus-ui:
            order: 8
        default_requests_memory:
          title: Default Requests Memory
          type: string
          description: Default memory requests of containers in the namespace. e.g.
            128Mi, 256Mi, 512Mi, 1Gi
          default: ""
          nullable: true
          x-walrus-ui:
            order: 9
        walrus_metadata_service_name:
          title: Walrus Metadata Service Name
          type: string
          description: Walrus metadata service name.
          default: ""
          nullable: true
          x-walrus-ui:
            order: 10
        walrus_metadata_namespace_name:
          title: Walrus Metadata Namespace Name
          type: string
          description: Walrus metadata namespace name.
          default: ""
          nullable: true
          x-walrus-ui:
            order: 11
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          nullable: true
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            order: 12
